apiVersion: serving.knative.dev/v1 # Current version of Knative
kind: Service
metadata:
  name: f2 # The name of the app
  namespace: default # The namespace the app will use
spec:
  template:
    spec:
      containers:
        - image: plamenppetrov/f2 # Reference to the image of the app
