# MIT License
#
# Copyright (c) 2022 Dilina Dehigama and EASE Lab
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
name: Run scheduled experiments

on: 
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'
  
jobs:
  build_client:
    name: Build framework
    runs-on: self-hosted
    env:
      working-directory: ./src
    steps:
      - name: Configure AWS credentials using EASE lab account
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: us-west-2

      - name: Setup go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - name: Grant Permission
        run:  |
          sudo chown -R $USER:$USER /home/ubuntu/actions-runner/_work/STeLLAR

      - name: Install dependencies
        run: sudo apt update && sudo apt install -y libsnmp-dev build-essential zip docker.io

      - name: Check out code into the Go module directory
        uses: actions/checkout@v3
        with:
          ref: continuous-benchmarking

      - name: Check syntax
        uses: golangci/golangci-lint-action@v3.3.1
        with:
          working-directory: ${{env.working-directory}}
          args: --timeout 5m --skip-dirs raw-code
          skip-cache: true
          skip-pkg-cache: true
          skip-build-cache: true

      - name: Clean and build client binary
        working-directory: ${{env.working-directory}}
        run: |
          sudo docker rm -f temp
          sudo docker build -t stellar .
          sudo docker create --name temp stellar /bin/bash

      - name: Package client artifact
        run: |
          sudo mkdir -p "setup/deployment/raw-code"
          sudo docker cp temp:/app/stellar ./main
          sudo docker cp temp:/app/setup/deployment/raw-code/functions setup/deployment/raw-code/functions
          sudo cp -r ./continuous-benchmarking/experiments continuous-experiments
          tar -czvf build.tar ./main ./setup/deployment/raw-code/functions ./continuous-experiments

      - name: Upload client artifact
        uses: actions/upload-artifact@v3
        with:
          name: STeLLAR-build
          path: build.tar
          retention-days: 1

  test_aws:
    name: Unit tests (incl. AWS API tests) and AWS integration tests
    needs: [ build_client ]
    runs-on: ubuntu-latest
    env:
      working-directory: ./src
    steps:

      - name: Warm Function Invocation - Baseline
        working-directory: ${{env.working-directory}}
        run: ./stellar -a 356764711652 -o latency-samples -g endpoints -c ../continuous-benchmarking/experiments/warm-function-invocations/warm-baseline-warmup-aws.json

      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: Download client artifact
        uses: actions/download-artifact@v3
        with:
          name: STeLLAR-build

      - name: Configure AWS credentials using EASE lab account
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: us-west-1

      - name: Untar client build
        working-directory: ${{env.working-directory}}
        run: tar --strip-components=1 -xvf ../build.tar -C .

      - name: Warm Function Invocation Test
        working-directory: ${{env.working-directory}}
        run: sudo ./main -a 737822989323 -o latency-samples -g endpoints -c continuous-experiments/warm-function-invocations/warm-baseline-aws.json
