name: feature-serverless-framework-deployment
on:
  push:
    branches:
      - feature-serverless-framework-deployment
  pull_request:
    branches:
      - feature-serverless-framework-deployment

jobs:
  check_syntax:
    name: Check syntax
    runs-on: ubuntu-22.04
    env:
      working-directory: ./src
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Check syntax
        uses: golangci/golangci-lint-action@v2.5.2
        with:
          working-directory: ${{env.working-directory}}
          args: --timeout 5m --skip-dirs raw-code
          skip-pkg-cache: true
          skip-build-cache: true

  build_client:
    name: Build framework
    runs-on: ubuntu-22.04
    env:
      working-directory: ./src
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Build client binary
        working-directory: ${{env.working-directory}}
        run: |
          docker build -t stellar .
          docker create --name temp stellar /bin/bash
      - name: Package client artifact
        run: |
          mkdir -p 'setup/deployment/raw-code'
          docker cp temp:/app/stellar ./main
          docker cp temp:/app/setup/deployment/raw-code/functions setup/deployment/raw-code/functions
          tar -czvf build.tar ./main ./setup/deployment/raw-code/functions

      - name: Upload client artifact
        uses: actions/upload-artifact@v2
        with:
          name: STeLLAR-build
          path: build.tar
          retention-days: 1

  unit_tests:
    name: Unit tests
    strategy:
      matrix:
        path:
          [
            ./setup/test/...,
            ./benchmarking/...,
            ./util/...,
            ./setup/building/test/...,
            ./setup/code-generation/test/...,
            ./setup/deployment/packaging/test/...,
            ./setup/deployment/connection/...,
          ]
    needs: [build_client]
    runs-on: ubuntu-22.04
    env:
      working-directory: ./src
      DOCKER_HUB_USERNAME: ${{secrets.DOCKER_HUB_USERNAME}}
      DOCKER_HUB_ACCESS_TOKEN: ${{secrets.DOCKER_HUB_ACCESS_TOKEN}}
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Configure AWS credentials using EASE lab account
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: us-west-1

      - id: "auth"
        name: Configure GCR credentials
        uses: "google-github-actions/auth@v1"
        with:
          credentials_json: "${{secrets.GCR_CREDENTIALS}}"

      - name: "Set up gcloud"
        uses: "google-github-actions/setup-gcloud@v1"
        with:
          version: ">= 363.0.0"
      - name: Set up Go 1.21
        uses: actions/setup-go@v2
        with:
          go-version: 1.21

      - name: Download client artifact
        uses: actions/download-artifact@v2
        with:
          name: STeLLAR-build

      - name: Untar client build
        working-directory: ${{env.working-directory}}
        run: tar --strip-components=1 -xvf ../build.tar -C .

      - name: Unit tests
        working-directory: ${{env.working-directory}}
        run: go test -short -v ${{matrix.path}}

  integration_tests:
    name: Integration tests
    needs: [build_client]
    runs-on: ubuntu-22.04
    env:
      working-directory: ./src
      DOCKER_HUB_USERNAME: ${{secrets.DOCKER_HUB_USERNAME}}
      DOCKER_HUB_ACCESS_TOKEN: ${{secrets.DOCKER_HUB_ACCESS_TOKEN}}
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Configure AWS credentials using EASE lab account
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: us-west-1

      - id: "auth"
        name: Configure GCR credentials
        uses: "google-github-actions/auth@v1"
        with:
          credentials_json: "${{secrets.GCR_CREDENTIALS}}"

      - name: "Set up gcloud"
        uses: "google-github-actions/setup-gcloud@v1"
        with:
          version: ">= 363.0.0"

      - name: Set up Go 1.21
        uses: actions/setup-go@v2
        with:
          go-version: 1.21

      - name: Set up Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Install serverless framework
        run: npm install -g serverless

      - name: Download client artifact
        uses: actions/download-artifact@v2
        with:
          name: STeLLAR-build

      - name: Untar client build
        working-directory: ${{env.working-directory}}
        run: tar --strip-components=1 -xvf ../build.tar -C .

      - name: Prepare benchmarking functions
        run: |
          mkdir -p 'setup/deployment/raw-code'
          cp -R ./src/setup/deployment/raw-code/functions setup/deployment/raw-code/functions
          mkdir -p './src/latency-samples'

      - name: Integration Tests
        working-directory: ${{env.working-directory}}
        run: go test -short -v ./setup/integration-test/...

  e2e_aws:
    name: AWS e2e test
    needs: [build_client, integration_tests]
    runs-on: ubuntu-22.04
    env:
      working-directory: ./src
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Configure AWS credentials using EASE lab account
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: us-west-1

      - name: Set up Go 1.21
        uses: actions/setup-go@v2
        with:
          go-version: 1.21

      - name: Set up Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Install serverless framework
        run: npm install -g serverless

      - name: Download client artifact
        uses: actions/download-artifact@v2
        with:
          name: STeLLAR-build

      - name: Untar client build
        working-directory: ${{env.working-directory}}
        run: tar --strip-components=1 -xvf ../build.tar -C .

      - name: Prepare benchmarking functions
        run: |
          mkdir -p 'setup/deployment/raw-code'
          cp -R ./src/setup/deployment/raw-code/functions setup/deployment/raw-code/functions
          mkdir -p './src/latency-samples'

      - name: AWS end-to-end test for Python
        working-directory: ${{env.working-directory}}
        run: ./main --o latency-samples --c ../experiments/tests/aws/hellopy.json --s true

      - name: AWS end-to-end test for Go
        working-directory: ${{env.working-directory}}
        run: ./main --o latency-samples --c ../experiments/tests/aws/hellogo.json --s true

      - name: AWS end-to-end test for Java
        working-directory: ${{env.working-directory}}
        run: ./main --o latency-samples --c ../experiments/tests/aws/hellojava-snapstart.json --s true

  e2e_gcr:
    name: GCR e2e test
    needs: [build_client, integration_tests]
    runs-on: ubuntu-22.04
    env:
      working-directory: ./src
      DOCKER_HUB_USERNAME: ${{secrets.DOCKER_HUB_USERNAME}}
      DOCKER_HUB_ACCESS_TOKEN: ${{secrets.DOCKER_HUB_ACCESS_TOKEN}}
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - id: "auth"
        name: Configure GCR credentials
        uses: "google-github-actions/auth@v1"
        with:
          credentials_json: "${{secrets.GCR_CREDENTIALS}}"

      - name: "Set up gcloud"
        uses: "google-github-actions/setup-gcloud@v1"
        with:
          version: ">= 363.0.0"

      - name: Set up Go 1.21
        uses: actions/setup-go@v2
        with:
          go-version: 1.21

      - name: Set up Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Download client artifact
        uses: actions/download-artifact@v2
        with:
          name: STeLLAR-build

      - name: Untar client build
        working-directory: ${{env.working-directory}}
        run: tar --strip-components=1 -xvf ../build.tar -C .

      - name: Prepare benchmarking functions
        run: |
          mkdir -p 'setup/deployment/raw-code'
          cp -R ./src/setup/deployment/raw-code/functions setup/deployment/raw-code/functions
          mkdir -p './src/latency-samples'

      - name: GCR end-to-end test for Python
        working-directory: ${{env.working-directory}}
        run: ./main --o latency-samples --c ../experiments/tests/gcr/hellopy.json --s true

      - name: GCR end-to-end test for Go
        working-directory: ${{env.working-directory}}
        run: ./main --o latency-samples --c ../experiments/tests/gcr/hellogo.json --s true

      - name: GCR end-to-end test for Java
        working-directory: ${{env.working-directory}}
        run: ./main --o latency-samples --c ../experiments/tests/gcr/hellogo.json --s true
