name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Entire Pipeline
    runs-on: ubuntu-18.04
    env:
      working-directory: ./client/src
    steps:
    
    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.15

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
        
    - name: Check Syntax
      uses: Jerome1337/golint-action@v1.0.2

    - name: Get dependencies
      working-directory: ${{env.working-directory}}
      run: |
        go get -v -t -d ./...
        if [ -f Gopkg.toml ]; then
            curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
            dep ensure
        fi
        
    - name: Build
      working-directory: ${{env.working-directory}}
      run: GOOS=linux go build -race -v -a
      
    - name: Unit Tests
      working-directory: ${{env.working-directory}}
      run: go test -cover -v ./...

    - name: Integration Test
      working-directory: ${{env.working-directory}}
      run: |
        mkdir -p "../latency-samples"
        touch ../gateways.csv
        echo "Gateway ID" >> ../gateways.csv
        ./client --o "../latency-samples" --c "../experiments/tests/test.json"
