name: golangci-lint
on:
  push:
    branches:
      - feature-serverless-framework-deployment
  pull_request:
    branches:
      - feature-serverless-framework-deployment

jobs:
  golangci:
    name: GolangCI Lint
    runs-on: self-hosted
    env:
      working-directory: ./src
    steps:
      - name: Setup go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Check out code into the Go module directory
        uses: actions/checkout@v3
        with:
          ref: feature-serverless-framework-deployment

      - name: Check syntax
        uses: golangci/golangci-lint-action@v3.3.1
        with:
          working-directory: ${{env.working-directory}}
          args: --timeout 5m --skip-dirs raw-code
          skip-cache: true
          skip-pkg-cache: true
          skip-build-cache: true
