name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: vHive-bench Pipeline
    runs-on: ubuntu-18.04
    env:
      working-directory: ./client/src
    steps:
    
    - name: Set up Go 1.15
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
        
    - name: Check Syntax
      uses: Jerome1337/golint-action@v1.0.2

    - name: Get dependencies
      working-directory: ${{env.working-directory}}
      run: |
        go get -v -t -d ./...
        if [ -f Gopkg.toml ]; then
            curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
            dep ensure
        fi
        
    - name: Build AWS producer-consumer function
      working-directory: ./client/src/setup/deployment/raw-code/producer-consumer/go1.x/aws
      run: |
        CGO_ENABLED=0 GOOS=linux go build -v -o handler main.go
        
    - name: Build vHive producer-consumer function
      working-directory: ./client/src/setup/deployment/raw-code/producer-consumer/go1.x/vhive
      run: |
        CGO_ENABLED=0 GOOS=linux go build -v -o handler main.go
        
    - name: Build client
      working-directory: ${{env.working-directory}}
      run: |
        GOOS=linux go build -race -v -a
      
    - name: Configure AWS credentials using EASE lab account
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-1
      
    - name: Unit Tests
      working-directory: ${{env.working-directory}}
      run: go test -short -cover -v ./...

    - name: Burstiness ZIP Package Test
      working-directory: ${{env.working-directory}}
      run: |
        mkdir -p "../latency-samples"
        ./client --o "../latency-samples" --c "../experiments/tests/AWS/burstiness-zip-package.json"

    - name: Burstiness Image Package Test
      working-directory: ${{env.working-directory}}
      run: |
        mkdir -p "../latency-samples"
        ./client --o "../latency-samples" --c "../experiments/tests/AWS/burstiness-image-package.json"

    - name: Data Transfer Integration Test
      working-directory: ${{env.working-directory}}
      run: |
        mkdir -p "../latency-samples"
        ./client --o "../latency-samples" --c "../experiments/tests/AWS/data-transfer.json"
