name: Run SnapStart Random Memory Read Experiments (AWS)

on:
  workflow_dispatch:
  push:
    branches:
      - snapstart-exp

jobs:
  build_client:
    name: Build framework
    runs-on: ubuntu-latest
    env:
      working-directory: ./src
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v4
        with:
          ref: snapstart-exp

      - name: Set up Go 1.21
        uses: actions/setup-go@v3
        with:
          go-version: 1.21

      - name: Build client binary
        working-directory: ${{env.working-directory}}
        run: env GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -o stellar main.go

      - name: Package client artifact
        working-directory: ${{env.working-directory}}
        run: tar -czvf build.tar ./stellar

      - name: Upload client artifact
        uses: actions/upload-artifact@v3
        with:
          name: STeLLAR-build
          path: ${{env.working-directory}}/build.tar
          retention-days: 1

  snapstart-exp:
    name: AWS SnapStart Experiments
    needs: build_client
    runs-on: [ self-hosted, aws ]
    strategy:
      matrix:
        size:
          [
            128,
            256, 
            512
          ]
    timeout-minutes: 1440
    env:
      working-directory: src
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}

    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v4
        with:
          ref: snapstart-exp

      - name: Configure AWS credentials using EASE lab account
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: us-west-1

      - name: Set up Node.js 16.16.0
        uses: actions/setup-node@v3
        with:
          node-version: 16.16.0

      - name: Download client artifact
        uses: actions/download-artifact@v3
        with:
          name: STeLLAR-build

      - name: Untar client build
        working-directory: ${{ env.working-directory }}
        run: tar --strip-components=1 -xvf ../build.tar -C .

      - name: AWS Cold Function Invocation - SnapStart Sequential Memory Read
        working-directory: ${{ env.working-directory }}
        run: ./stellar -a 356764711652 -o latency-samples -c ../experiments/tests/aws/hellojava-snapstart-function-size-${{matrix.size}}-rand.json 

      - uses: actions/upload-artifact@v3
        with:
          name: snapstart-aws-rand-${{matrix.size}}
          path: ${{ env.working-directory }}/latency-samples
